# Stolen shamelessly from https://github.com/probabilistic-numerics/probnum/blob/6659bb6a8d279bad94b6b1d6ea7a535a99fa0855/.github/workflows/run-notebooks.yml
name: Jupyter Notebooks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get update
          pip install .
      - name: Execute all notebooks with nbconvert
        run: |
          for file in $(find -wholename "./exp/*.ipynb")
          do
              jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 $file
          done
